(()=>{'use strict';
const $=id=>document.getElementById(id),scene=$('scene'),art=$('art'),reaction=$('reaction'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const sections={home:{title:'Welcome to Satish OS',caption:'A workspace built around reliable platforms, people and progress.',action:'#about',label:'Get to know me'},about:{title:'A little about me',caption:'7+ years across technical support, customer success, production operations and automation.',action:'#about',label:'Read my story'},experience:{title:'My career journey',caption:'Explore my verified roles, responsibilities and cross-functional work.',action:'#experience',label:'View experience'},projects:{title:'Explore the projects',caption:'See how I approach monitoring, automated reporting and operational coordination.',action:'#projects',label:'View projects'},skills:{title:'My toolkit',caption:'Apps Script, REST APIs, incident response, monitoring and stakeholder collaboration.',action:'#skills',label:'Explore skills'},resume:{title:'Professional résumé',caption:'Review my experience or request the latest résumé.',action:'#resume',label:'View résumé'},contact:{title:"Let's connect",caption:'Open a conversation about technical operations, reliability or leadership.',action:'#contact',label:'Contact me'},simulation:{title:'Incident response lab',caption:'Run a fictional production incident and explore investigation, mitigation and recovery.',action:'#simulation',label:'Start simulation'}};
const mk=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e};
let active='home',helloTimer=null,blinkTimer=null,hideTimer=null;
const panel=mk('div','scene-panel');panel.id='scenePanel';panel.innerHTML='<div class="panel-kicker">EXPLORE MY WORKSPACE</div><strong id="sceneTitle">Welcome to Satish OS</strong><p id="sceneCaption">Explore my professional work.</p><a id="sceneAction" class="panel-link" href="#about">Get to know me →</a><button type="button" id="scenePanelClose" aria-label="Close scene panel">×</button>';scene.append(panel);
$('scenePanelClose').onclick=()=>panel.classList.remove('show');
const eyeLeft=mk('span','eye-blink left'),eyeRight=mk('span','eye-blink right');scene.append(eyeLeft,eyeRight);
function positionEyes(){const r=scene.getBoundingClientRect();if(!r.width)return;const iw=1110,ih=675,scale=Math.max(r.width/iw,r.height/ih)*1.035,ox=(r.width-iw*scale)/2,oy=(r.height-ih*scale)/2;[[eyeLeft,231,194,31,11,-14],[eyeRight,313,181,28,10,-11]].forEach(([el,x,y,w,h,angle])=>{el.style.left=ox+x*scale+'px';el.style.top=oy+y*scale+'px';el.style.width=Math.max(12,w*scale)+'px';el.style.height=Math.max(5,h*scale)+'px';el.style.transform='rotate('+angle+'deg)'})}
function blink(){if(reduced)return;scene.classList.add('is-blinking');setTimeout(()=>scene.classList.remove('is-blinking'),145);blinkTimer=setTimeout(blink,2300+Math.random()*3700)}
function say(text){reaction.textContent=text;reaction.classList.add('show');clearTimeout(hideTimer);hideTimer=setTimeout(()=>reaction.classList.remove('show'),3600)}
function setMode(mode,openPanel=true){const item=sections[mode]||sections.home;active=mode;scene.dataset.mode=mode;scene.classList.remove('scene-react');void scene.offsetWidth;scene.classList.add('scene-react');say(item.title);$('sceneTitle').textContent=item.title;$('sceneCaption').textContent=item.caption;const link=$('sceneAction');link.textContent=item.label+' →';link.setAttribute('href',item.action);panel.classList.toggle('show',openPanel);document.querySelectorAll('.shortcut').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+mode));}
let intro=null,introTimer=null;
function closeIntro(destination){if(!intro||intro.hidden)return;clearTimeout(introTimer);intro.classList.add('leaving');setTimeout(()=>{intro.hidden=true;intro.classList.remove('leaving');document.body.classList.remove('intro-open');if(destination){const target=document.querySelector(destination);target?.scrollIntoView({behavior:reduced?'instant':'smooth'})}setMode(destination?destination.slice(1):'home',!!destination)},reduced?0:470)}
function showIntro(){if(reduced){setMode('home',false);return}clearTimeout(introTimer);intro.hidden=false;intro.classList.remove('leaving');document.body.classList.add('intro-open');intro.querySelector('.intro-message').textContent='Hi, welcome to my workspace.';intro.querySelector('.intro-art').classList.remove('wave-in');void intro.offsetWidth;intro.querySelector('.intro-art').classList.add('wave-in');introTimer=setTimeout(()=>closeIntro(),5800)}
intro=mk('div','intro-screen');intro.id='introScreen';intro.setAttribute('role','region');intro.setAttribute('aria-label','Animated portfolio introduction');intro.innerHTML='<div class="intro-copy"><span class="intro-eyebrow">SATISH.OS / WELCOME</span><h2>Hi, I\'m <em>Satish Tiwari.</em></h2><p>Technical operations · automation · cross-functional leadership</p><div class="intro-actions"><button type="button" class="intro-enter">Enter my workspace →</button><a class="intro-explore" href="#projects">Explore projects</a></div><span class="intro-hint">A short cinematic introduction · You can skip at any time</span></div><div class="intro-art"><img alt="Illustrated character inspired by Satish waves behind a laptop in a sunlit workspace" id="introArt"><div class="intro-speech intro-message" aria-live="polite">Hi, welcome to my workspace.</div><div class="intro-wave" aria-hidden="true">👋</div></div><button class="intro-skip" type="button" aria-label="Skip welcome animation">Skip intro ↗</button><div class="intro-progress" aria-hidden="true"></div>';
document.body.append(intro);$('introArt').src=art.currentSrc||art.src;
intro.querySelector('.intro-enter').onclick=()=>closeIntro();
intro.querySelector('.intro-explore').onclick=e=>{e.preventDefault();closeIntro('#projects')};intro.querySelector('.intro-skip').onclick=()=>closeIntro();
$('intro').onclick=()=>showIntro();$('intro').textContent='▶ Watch welcome animation';$('hello').onclick=()=>{setMode('home',true);say('Hello! Thanks for visiting 👋')};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!intro.hidden)closeIntro()});
const names=new Set(Object.keys(sections));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{const key=a.getAttribute('href').slice(1);if(names.has(key))setMode(key,key!=='home')}));
if(!reduced&&matchMedia('(pointer:fine)').matches){scene.addEventListener('pointermove',e=>{const r=scene.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;art.style.setProperty('--mx',(-x*8).toFixed(1)+'px');art.style.setProperty('--my',(-y*5).toFixed(1)+'px');scene.style.setProperty('--look-x',(x*6).toFixed(1)+'px');scene.style.setProperty('--look-y',(y*4).toFixed(1)+'px')});scene.addEventListener('pointerleave',()=>{art.style.setProperty('--mx','0px');art.style.setProperty('--my','0px');scene.style.setProperty('--look-x','0px');scene.style.setProperty('--look-y','0px')})}
function render(s,c,l,e,t,d){$('status').textContent=s;$('status').className='status '+c;$('latency').textContent=l;$('errors').textContent=e;$('stage').textContent=t;$('detail').textContent=d}
$('trigger').onclick=()=>{render('● INCIDENT DETECTED','bad','2,450 ms','12.8%','Investigating','Elevated API errors. Investigate impact, notify responders and coordinate mitigation.');$('trigger').disabled=true;$('mitigate').disabled=false;setMode('simulation',true)};
$('mitigate').onclick=()=>{render('● RECOVERING','warn','120 ms','0.4%','Verifying','Mitigation applied. Verify recovery and monitor stability.');$('mitigate').disabled=true;setMode('simulation',true)};
$('reset').onclick=()=>{render('● OPERATIONAL','','85 ms','0.1%','Normal','Monitoring active. Trigger a simulated incident.');$('trigger').disabled=false;$('mitigate').disabled=true};
window.addEventListener('resize',positionEyes,{passive:true});art.addEventListener('load',positionEyes,{once:true});positionEyes();if(!reduced){blinkTimer=setTimeout(blink,1500);setTimeout(showIntro,180)}else intro.hidden=true;
})();